use_frameworks!

target 'ZaloSDKFramework_Example' do
  pod 'ZaloSDKFramework', :path => '../'
  pod 'AlamofireImage', '~> 3.3'
  pod 'Eureka'
  
  target 'ZaloSDKFramework_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  end
end
